name: Build and Release (Ubuntu 22.04)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-22.04
    name: Build Release Binary

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/sentrix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}