name: Release Gateway Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            suffix: linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: macos-amd64

    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.suffix }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: stable

      - name: Install target triple
        run: rustup target add ${{ matrix.target }}

      - name: Install musl tools (for Linux static linking)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/mytool dist/mytool
          cd dist
          zip mytool-${{ matrix.suffix }}.zip mytool

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/mytool-${{ matrix.suffix }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}